### ISSUE TITLE
Suresh's comment on section 3.4.1.

### ISSUE THREAD

**Issue by evyncke** [IPv6-mPvD/mpvd-ietf-drafts#18]
> * Section 3.4.1
> 
> Not sure if this is the best way to specify stateful DHCPv6. There are stateful options that will not be under a PIO (e.g. IA_PD). I think this document should limit itself to IA_NA and possibly IA_TA. Leaving this unbounded does not seem to be a good idea. Thoughts?

**Comment by evyncke** [comment]
Pierre @Oryon actually wanted this 'unbounded statement' to also cover IA_PD implicitly... The sentence is unclear on purpose and to avoid lengthy discussion.

I would prefer to keep it like it is and reply unicast to Suresh with the above or simply upload a revised I-D ignoring Suresh's comment.

Pierre, what do you think ?

**Comment by tfpauly** [comment]
I'm fine with leaving this as it is, if you want to reply directly to Suresh on this one.

**Comment by Oryon** [comment]
Early versions of the draft were trying to do something with the DHCPv6 server's link-local address or MAC address to tie DHCPv6 servers and RAs. But this was a hack.
Using the PIOs is more elegant, since it does not make the assumption that DHCPv6 packets are sent by the router.
It is still possible to use PIOs for delegated prefixes by advertising the prefix (or a larger prefix) with SLAAC disabled and no o flag.
Another option would be to use RIOs. That would be in line with RFC7084. But not every system supports RIOs.
